version: "3" # versão do yaml

services:
  presentation-test-db:
    image: postgres:latest
    container_name: presentation-test-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "presentation"
    ports:
      - "5432:5432"
    volumes:
      - "~/data/postgres:/var/lib/postgresql/data:rw"
